//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementAPI.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryManagementAPI.Core.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied!.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author already exists!.
        /// </summary>
        public static string AUTHOR_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("AUTHOR_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author cannot be deleted!.
        /// </summary>
        public static string AUTHOR_NOT_DELETABLE {
            get {
                return ResourceManager.GetString("AUTHOR_NOT_DELETABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author cannot be edited!.
        /// </summary>
        public static string AUTHOR_NOT_EDITABLE {
            get {
                return ResourceManager.GetString("AUTHOR_NOT_EDITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author not found!.
        /// </summary>
        public static string AUTHOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("AUTHOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book already exists!.
        /// </summary>
        public static string BOOK_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("BOOK_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book cannot be deleted!.
        /// </summary>
        public static string BOOK_NOT_DELETABLE {
            get {
                return ResourceManager.GetString("BOOK_NOT_DELETABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book cannot be edited!.
        /// </summary>
        public static string BOOK_NOT_EDITABLE {
            get {
                return ResourceManager.GetString("BOOK_NOT_EDITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book not found!.
        /// </summary>
        public static string BOOK_NOT_FOUND {
            get {
                return ResourceManager.GetString("BOOK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This genre already exists!.
        /// </summary>
        public static string GENRE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("GENRE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This genre cannot be deleted!.
        /// </summary>
        public static string GENRE_NOT_DELETABLE {
            get {
                return ResourceManager.GetString("GENRE_NOT_DELETABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This genre cannot be edited!.
        /// </summary>
        public static string GENRE_NOT_EDITABLE {
            get {
                return ResourceManager.GetString("GENRE_NOT_EDITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre not found!.
        /// </summary>
        public static string GENRE_NOT_FOUND {
            get {
                return ResourceManager.GetString("GENRE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors in input data and try again!.
        /// </summary>
        public static string MODEL_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("MODEL_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful!.
        /// </summary>
        public static string SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! Please, try again!.
        /// </summary>
        public static string UNHANDLED_ERROR {
            get {
                return ResourceManager.GetString("UNHANDLED_ERROR", resourceCulture);
            }
        }
    }
}
